---
- name: Check for previous HKL2000 v720 install
  stat: path=/app/hkl2000/v720/bin
  register: hkl_orig
  tags: hkl2000_install

- name: Create HKL2000 v720 directory
  become: yes
  file:
    path: /app/hkl2000
    state: directory
    owner: root
    mode: 0755
  when: not hkl_orig.stat.exists
  register: hkl_dir
  tags: hkl2000_install

- name: Unpack the HKL2000 v720 source
  become: yes
  unarchive:
    src: /software/HKL2000/HKL2000_v720-Linux-x86_64.tar.gz
    dest: /app/hkl2000
  when: hkl_dir.changed
  register: hkl_unpack
  tags: hkl2000_install

- name: Move unpacked files to proper directory name
  become: yes
  command: "mv /app/hkl2000/HKL2000_v720-Linux-x86_64 /app/hkl2000/v720"
  when: hkl_unpack.changed
  register: hkl_move
  tags: hkl2000_install
