---
- name: Check for previous Moe 2019_0102 install
  stat: path=/app/moe/v2019.0102/bin
  register: moe_orig
  tags: moe_install

- name: Crate the Moe directory
  become: yes
  file:
    path: /app/moe
    state: directory
    owner: root
    mode: 0755
  when: not moe_orig.stat.exists
  register: moe_dir
  tags: moe_install

- name: Run the Moe 2019_0102 silent installer
  command: "sh /software/Moe/moe2019_0102_installer_linux64.bin -f /software/Moe/installer.properties -i silent"
  when: moe_dir.changed
  register: moe_setup
  tags: moe_install

- name: Move unpacked files to proper directory name
  become: yes
  command: "mv /app/moe/moe_2019.0102 /app/moe/v2019.0102"
  when: moe_setup.changed
  register: moe_move
  tags: moe_install

- name: Copy in the Moe license
  command: "cp /software/Moe/license.dat /app/moe/v2019.0102/"
  when: moe_setup.changed
  register: moe_license
  tags: moe_install
