---

- name:
  include_vars:
    file: main.yml 

- name: make sure /etc/hosts has the correct information for the primary
  lineinfile:
    path: /etc/hosts
    line:
      {{ nisprimaryip }} {{ nisprimaryhostname }}

- name: make sure /etc/hosts has the correct information for the secondary
  lineinfile:
    path: /etc/hosts
    line:
      {{ ansible_default_ipv4.address }}  {{ nissecondaryhostname }}

- name: Install the correct packages.
  yum:
    name:
      - ypserv
      - rpcbind
      - yp-tools
      - nss-pam-ldapd
      - nss_nis
      - ypbind
      - authconfig-gtk
    state: present

- name: make sure ypdomain is  set
  command: ypdomainname {{ nisdomain }}

 - name: edit to /etc/sysconfig/network
   lineinfile:
    path: /etc/sysconfig/network
    line:
      NISDOMAIN={{ nisdomain }}

- name: Edit to /etc/yp.conf
  blockinfile:
    path: /etc/yp.conf
    block:
      ypserver {{ nisprimaryhostname }}
      domain {{ nisdomain }} server {{ nisprimaryip }}
      domain {{ nisdomain }} server {{ ansible_default_ipv4.address }}

 - name: Ensure rpcbind is enabled.
   systemd:
    name: rpcbind
    enabled: yes
    state: started

- name: Ensure ypserv is enabled.
  systemd:
    name: ypserv
    enabled: yes
    state: started

- name: Ensure ypxfrd is enabled.
  systemd:
    name: ypxfrd
    enabled: yes
    state: started

 - name: Ensure yppasswdd is enabled.
   systemd:
    name: yppasswdd
    enabled: yes
    state: started

 - name: run ypinit
   command: /usr/lib64/yp/ypinit -s {{ nisprimaryhostname }}

 - name: Restart ypbind
   systemd:
    name: ypbind
    state: restarted

- name: enablenis
   command: authconfig --enablenis --enablemkhomedir –update
