---
- name: Check for previous XDS 20200417 install
  stat: path=/app/xds/v20200417
  register: xds_orig
  tags: xds_install

- name: Create XDS directory
  become: yes
  file:
    path: /app/xds
    state: directory
    owner: root
    mode: 0755
  when: not xds_orig.stat.exists
  register: xds_dir
  tags: xds_install

- name: Download the XDS 20200417 tar ball
  get_url:
    url: ftp://ftp.mpimf-heidelberg.mpg.de/pub/kabsch/XDS-INTEL64_Linux_x86_64.tar.gz
    dest: /app/xds/XDS-INTEL64_Linux_x86_64.tar.gz
  when: xds_dir.changed
  register: xds_source
  tags: xds_install

- name: Unpack the XDS 20200417 source
  become: yes
  unarchive:
    src: /app/xds/XDS-INTEL64_Linux_x86_64.tar.gz
    dest: /app/xds
  when: xds_source.changed
  register: xds_unpack
  tags: xds_install

#  - name: Create XDS version directory
#    become: yes
#    file:
#      path: /app/xds/v20200417
#      state: directory
#      owner: root
#      mode: 0755
#    when: xds_unpack.changed
#    register: xds_dir2
#
#  - name: Copy XDS source files to destination
#    command: "cp /app/xds/XDS-INTEL64_Linux_x86_64 /app/xds/v20200417"
#    when: xds_dir2.changed
#    register: xds_copy

- name: Move unpacked files to proper directory name
  become: yes
  command: "mv /app/xds/XDS-INTEL64_Linux_x86_64 /app/xds/v20200417"
  when: xds_unpack.changed
  register: xds_move
  tags: xds_install

- name: Remove XDS install files
  become: yes
  command: "rm -rf /app/xds/XDS-INTEL64_Linux_x86_64*"
  when: xds_move.changed
  register: xds_clean
  tags: xds_install
