---
- hosts: all
  serial: 5
  gather_facts: no
  pre_tasks: 
    - setup:
    
  include_roles:
    - required_rpms
    - nomachine
    - globalphasing
    - hkl2000
    - install_ccp4
    - moe
    - phenix
    - schodinger
